kind: Pod
apiVersion: v1
metadata:
  name: stock-ticker
  labels:
    app: stock-ticker
spec:
  containers:
    - name: stock-ticker
      image: 'mabriot/stock-ticker:1.0.0'
      envFrom:
      - configMapRef:
          name: env-var
      - secretRef:
          name: api-key
---
kind: Service
apiVersion: v1
metadata:
  name: stock-ticker-service
spec:
  selector:
    app: stock-ticker
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-ticker-ingress
spec:
  rules:
  - host: "stockticker.example.com"
    http:
      paths:
      - pathType: Prefix
        path: "/api/closing-prices"
        backend:
          service:
            name: stock-ticker-service
            port:
              number: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key
type: Opaque
data:
  APIKEY: QzIyN1dEOVczTFVWS1ZWOQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-var
data:
  SYMBOL: "MSFT"
  NDAYS: "7"
---